import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Background from "@/components/Background";
import { Plus_Jakarta_Sans } from "next/font/google";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-gray-50 min-h-screen flex flex-col relative`}>
        
        <Background /> {/* ใส่ตรงนี้ทีเดียว ทุกหน้าจะมีพื้นหลังเหมือนกันหมด */}
        
        <Navbar />
        
        <main className="max-w-7xl mx-auto w-full p-6 pt-24 pb-10 flex-grow">
          {children}
        </main>
        
        <Footer />
        
      </body>
    </html>
  );
}